
package vue;
import controleur.*;
import java.awt.Point;
import javax.swing.JPanel;
import javax.swing.*;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JColorChooser;

/**
 *
 * @author MILIA Juvaldo Wisman
 */
public class MaFenetre extends JFrame {

    static String tool = "Pinceau";

    /**
     * Creates new form NewJFrame
     */
    public int Eff = 0;
    
    public static boolean RetourAction = false;
    public static boolean AvanceAction = false;
    public static Color LaCouleur = Color.BLACK ;
    public static int LaTaille = 10;
    

    
    public static DrawSpace canvas;
    public MaFenetre() {
        
        initComponents();
        canvas = new DrawSpace(brushSize.getValue());
        addDrawSpace(canvas);
        
    }
    
    //Foction pour tout effacer
    public void Efface(){
        if(Eff == 1){
            canvas.clear();
            System.out.println(Eff);
            Eff--;
        }
    }
    
    //Sauvegarder
    public void Save(){
        Save Sauvegarder = new Save(canvas);
        Sauvegarder.WhereSave();
    }
    
    //Chabger de couleur
    private void Couleur() {
        LaCouleur = JColorChooser.showDialog(this, "Choisissez une couleur", LaCouleur); 
        ColUsed.setBackground(LaCouleur);
    }

    /**
     *
     * @param <P>
     * @param <JFrame>
     * @param canvas1
     */
    public <P extends JPanel,JFrame> void  addDrawSpace(P canvas1){
        
        canvas1.setBackground(new Color(255, 255, 255));
        jPanel2.add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 840, 510));
    }
    protected Point lastPoint;
    private int X,Y,X1,Y1;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Couleur = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        brushSize = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Save = new javax.swing.JButton();
        Avance = new javax.swing.JButton();
        carre = new javax.swing.JButton();
        Pinceau = new javax.swing.JButton();
        Ligne = new javax.swing.JButton();
        triangle = new javax.swing.JButton();
        cercle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Retour = new javax.swing.JButton();
        ColUsed = new javax.swing.JPanel();
        ColRouge = new javax.swing.JPanel();
        ColOrange = new javax.swing.JPanel();
        ColJaune = new javax.swing.JPanel();
        ColVert = new javax.swing.JPanel();
        ColBleu = new javax.swing.JPanel();
        ColBlack = new javax.swing.JPanel();
        Gomme = new javax.swing.JButton();
        Remplir = new javax.swing.JButton();
        Slected = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paint of Binome 4");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(229, 226, 226));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Couleur.setBackground(new java.awt.Color(229, 226, 226));
        Couleur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_Color_Wheel_32px.png"))); // NOI18N
        Couleur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Couleur.setFocusPainted(false);
        Couleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CouleurActionPerformed(evt);
            }
        });
        jPanel1.add(Couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, 30));

        Clear.setBackground(new java.awt.Color(229, 226, 226));
        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_synchronize_20px.png"))); // NOI18N
        Clear.setText("clear");
        Clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Clear.setFocusPainted(false);
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 70, 20));

        brushSize.setBackground(new java.awt.Color(229, 226, 226));
        brushSize.setValue(10);
        brushSize.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                brushSizeMouseDragged(evt);
            }
        });
        jPanel1.add(brushSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_Pencil_20px.png"))); // NOI18N
        jLabel1.setText("Reglage de Taille ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 140, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 70));

        Save.setBackground(new java.awt.Color(229, 226, 226));
        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_save_32px.png"))); // NOI18N
        Save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Save.setFocusPainted(false);
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 30));

        Avance.setBackground(new java.awt.Color(229, 226, 226));
        Avance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_right_32px.png"))); // NOI18N
        Avance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Avance.setFocusPainted(false);
        Avance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvanceActionPerformed(evt);
            }
        });
        jPanel1.add(Avance, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 30, 30));

        carre.setBackground(new java.awt.Color(229, 226, 226));
        carre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_rectangular_32px_1.png"))); // NOI18N
        carre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        carre.setFocusPainted(false);
        carre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carreActionPerformed(evt);
            }
        });
        jPanel1.add(carre, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 32, 32));

        Pinceau.setBackground(new java.awt.Color(229, 226, 226));
        Pinceau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_illustrator_32px.png"))); // NOI18N
        Pinceau.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pinceau.setFocusPainted(false);
        Pinceau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinceauActionPerformed(evt);
            }
        });
        jPanel1.add(Pinceau, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 32, 32));

        Ligne.setBackground(new java.awt.Color(229, 226, 226));
        Ligne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_line_32px.png"))); // NOI18N
        Ligne.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ligne.setFocusPainted(false);
        Ligne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LigneActionPerformed(evt);
            }
        });
        jPanel1.add(Ligne, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 32, 32));

        triangle.setBackground(new java.awt.Color(229, 226, 226));
        triangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_play_32px.png"))); // NOI18N
        triangle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        triangle.setFocusPainted(false);
        triangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangleActionPerformed(evt);
            }
        });
        jPanel1.add(triangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 32, 32));

        cercle.setBackground(new java.awt.Color(229, 226, 226));
        cercle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_circle_32px.png"))); // NOI18N
        cercle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cercle.setFocusPainted(false);
        cercle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercleActionPerformed(evt);
            }
        });
        jPanel1.add(cercle, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 32, 32));

        jLabel2.setText("Choix de couleur :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 120, 20));

        Retour.setBackground(new java.awt.Color(229, 226, 226));
        Retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_left_32px.png"))); // NOI18N
        Retour.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Retour.setFocusPainted(false);
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });
        jPanel1.add(Retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 30, 30));

        ColUsed.setBackground(new java.awt.Color(0, 0, 0));
        ColUsed.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        jPanel1.add(ColUsed, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 30, 30));

        ColRouge.setBackground(new java.awt.Color(255, 0, 0));
        ColRouge.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        ColRouge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColRougeMouseClicked(evt);
            }
        });
        jPanel1.add(ColRouge, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 30, 30));

        ColOrange.setBackground(java.awt.Color.orange);
        ColOrange.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        ColOrange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColOrangeMouseClicked(evt);
            }
        });
        jPanel1.add(ColOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 30, 30));

        ColJaune.setBackground(java.awt.Color.yellow);
        ColJaune.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        ColJaune.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColJauneMouseClicked(evt);
            }
        });
        jPanel1.add(ColJaune, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 30, 30));

        ColVert.setBackground(java.awt.Color.green);
        ColVert.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        ColVert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColVertMouseClicked(evt);
            }
        });
        jPanel1.add(ColVert, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 30, 30));

        ColBleu.setBackground(java.awt.Color.blue);
        ColBleu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        ColBleu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColBleuMouseClicked(evt);
            }
        });
        jPanel1.add(ColBleu, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 30, 30));

        ColBlack.setBackground(java.awt.Color.black);
        ColBlack.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        ColBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColBlackMouseClicked(evt);
            }
        });
        jPanel1.add(ColBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 30, 30));

        Gomme.setBackground(new java.awt.Color(229, 226, 226));
        Gomme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_eraser_32px.png"))); // NOI18N
        Gomme.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Gomme.setFocusPainted(false);
        Gomme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GommeActionPerformed(evt);
            }
        });
        jPanel1.add(Gomme, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 32, 32));

        Remplir.setBackground(new java.awt.Color(229, 226, 226));
        Remplir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_no_filling_32px.png"))); // NOI18N
        Remplir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Remplir.setFocusPainted(false);
        Remplir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemplirActionPerformed(evt);
            }
        });
        jPanel1.add(Remplir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 32, 32));

        Slected.setBackground(new java.awt.Color(229, 226, 226));
        Slected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_Select_Cursor_32px.png"))); // NOI18N
        Slected.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Slected.setFocusPainted(false);
        Slected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlectedActionPerformed(evt);
            }
        });
        jPanel1.add(Slected, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 32, 32));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 100));

        jPanel2.setBackground(new java.awt.Color(229, 226, 226));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1020, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // Savegarder la painture
        Save();
    }//GEN-LAST:event_SaveActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // pour effacer tout les travail sur le panel
        Eff++;
        Efface();
    }//GEN-LAST:event_ClearActionPerformed

    private void carreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carreActionPerformed
        // TODO add your handling code here:
        
        tool = "Rectangle";
    }//GEN-LAST:event_carreActionPerformed

    private void PinceauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinceauActionPerformed
        
        tool = "Pinceau";
    }//GEN-LAST:event_PinceauActionPerformed

    private void LigneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LigneActionPerformed
        // TODO add your handling code here:
        
        tool = "Ligne";

    }//GEN-LAST:event_LigneActionPerformed

    private void triangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangleActionPerformed
        // TODO add your handling code here:
        
        tool = "Triangle";
    }//GEN-LAST:event_triangleActionPerformed

    private void cercleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercleActionPerformed
        // TODO add your handling code here:
        
        tool = "Cercle";
    }//GEN-LAST:event_cercleActionPerformed

    private void CouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CouleurActionPerformed
        // changer de couleur
        Couleur();
    }//GEN-LAST:event_CouleurActionPerformed

    private void brushSizeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brushSizeMouseDragged
        // TODO add your handling code here:
        canvas.setBrushSize(brushSize.getValue());
    }//GEN-LAST:event_brushSizeMouseDragged

    private void AvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvanceActionPerformed
        AvanceAction = true;
        canvas.redo();
    }//GEN-LAST:event_AvanceActionPerformed

    private void GommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GommeActionPerformed
        
        tool = "Gomme";
    }//GEN-LAST:event_GommeActionPerformed

    private void ColRougeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColRougeMouseClicked

        LaCouleur = ColRouge.getBackground();
        ColUsed.setBackground(LaCouleur);
        //ColRouge.setBorder(border);
    }//GEN-LAST:event_ColRougeMouseClicked

    private void ColOrangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColOrangeMouseClicked
        LaCouleur = ColOrange.getBackground();
        ColUsed.setBackground(LaCouleur);
    }//GEN-LAST:event_ColOrangeMouseClicked

    private void ColJauneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColJauneMouseClicked
        LaCouleur = ColJaune.getBackground();
        ColUsed.setBackground(LaCouleur);
    }//GEN-LAST:event_ColJauneMouseClicked

    private void ColVertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColVertMouseClicked
        LaCouleur = ColVert.getBackground();
        ColUsed.setBackground(LaCouleur);
    }//GEN-LAST:event_ColVertMouseClicked

    private void ColBleuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColBleuMouseClicked
        LaCouleur = ColBleu.getBackground();
        ColUsed.setBackground(LaCouleur);
    }//GEN-LAST:event_ColBleuMouseClicked

    private void ColBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColBlackMouseClicked
        LaCouleur = ColBlack.getBackground();
        ColUsed.setBackground(LaCouleur);
    }//GEN-LAST:event_ColBlackMouseClicked

    private void RemplirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemplirActionPerformed

        tool = "Remplir";
    }//GEN-LAST:event_RemplirActionPerformed

    private void SlectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlectedActionPerformed
        
        tool = "Select";
    }//GEN-LAST:event_SlectedActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        RetourAction = true;
        canvas.undo();
        
    }//GEN-LAST:event_RetourActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Avance;
    private javax.swing.JButton Clear;
    private javax.swing.JPanel ColBlack;
    private javax.swing.JPanel ColBleu;
    private javax.swing.JPanel ColJaune;
    private javax.swing.JPanel ColOrange;
    private javax.swing.JPanel ColRouge;
    public static javax.swing.JPanel ColUsed;
    private javax.swing.JPanel ColVert;
    private javax.swing.JButton Couleur;
    private javax.swing.JButton Gomme;
    private javax.swing.JButton Ligne;
    private javax.swing.JButton Pinceau;
    private javax.swing.JButton Remplir;
    private javax.swing.JButton Retour;
    private javax.swing.JButton Save;
    private javax.swing.JButton Slected;
    public javax.swing.JSlider brushSize;
    private javax.swing.JButton carre;
    private javax.swing.JButton cercle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton triangle;
    // End of variables declaration//GEN-END:variables

}
